### ISSUE TITLE
There should be an extension for overlays

### ISSUE THREAD

**Issue by tapioaali** [tapioaali/GoogleMapsVaadin7#29]
The management of overlays should be moved to an extension. That would make it a lot easier to add new types of overlays and also keep the code cleaner. The extension should be a part of the current project so that old API wouldn't be broken. Just deprecate the old commands.

Overlays that should be part of this extension at the first stage:
- Marker (from original code, see also [PR27](https://github.com/tjkaal/GoogleMapsVaadin7/pull/27)).
- Polyline (from original code).
- Polygon (from original code).
- Info window (from orignal code.
- Circle (see [PR19](https://github.com/tjkaal/GoogleMapsVaadin7/pull/19) and [PR16](https://github.com/tjkaal/GoogleMapsVaadin7/pull/16)).

There should also be support for features missing from the original add-on:
- All overlays should be clickable (with proper RPCs).
- Investigate if drawing functionality could be a part of this extension too.
- Markers: z-index, anchoring of icon (see [PR27](#27))
- Caption support

Old issues closed when this was created: #6, #7, #9, #13, #14.

**Comment by thinwire** [comment]
This project is no longer being maintained here. It has moved to [https://github.com/parttio/Google-Maps-for-Vaadin](https://github.com/parttio/Google-Maps-for-Vaadin)

Thanks.
