### ISSUE TITLE
Remove multiple Markers fails 

### ISSUE THREAD

**Issue by HellaSolutions** [tapioaali/GoogleMapsVaadin7#32]
Hi,

Removing multiple markers at one time fails, just one marker is removed and in a cyclic way. At the first interaction only the "first" marker is removed, then only the "second" and so on.. 

Map version: 1.2.1
Vaadin version: 7.5.2

**Comment by tjkaal** [comment]
Could you provide an example UI that demonstrates the issue? I really don't have much time to work with this project and that would really help fixing the issue.

**Comment by tapioaali** [comment]
Is the issue still active? Anyway I'll take a look on this soon and if I'm able to replicate it I'll try to fix it to the next version.

**Comment by thinwire** [comment]
This project is no longer being maintained here. It has moved to [https://github.com/parttio/Google-Maps-for-Vaadin](https://github.com/parttio/Google-Maps-for-Vaadin)

Thanks.
