### ISSUE TITLE
Using Vaadin component as InfoWindow contents: how to remove?

### ISSUE THREAD

**Issue by aroneous** [tapioaali/GoogleMapsVaadin7#37]
Looking at the new feature to use a Vaadin component as the content of an InfoWindow (`GoogleMap#setInfoWindowContents(GoogleMapInfoWindow, Component)` method): I don't see a way to remove such a component once the InfoWindow is closed and discarded. Perhaps this is not a big concern in practice, but it seems like a feature that should be there.

Could this be added, or if you don't think it's needed, could you explain why?

**Comment by tjkaal** [comment]
IIRC that isn't currently possible but it definitely should be. I'll try to add that to the next version.

Current implementation is really minimal; I wanted to implement it without doing any hacks either with Vaadin or Google Maps which required some research that took most of the time I had. Most likely there are many weird bugs and missing API functions and I'll be adding/fixing them in the future. Keep them tickets coming :)
