### ISSUE TITLE
Map looses zoom and center on panel switch

### ISSUE THREAD

**Issue by mosi0815** [tapioaali/GoogleMapsVaadin7#42]
We have an application which uses multiple panels. On the left there's a menu to switch between them. Once a user presses a button the old one get's removed and the new one is added. The state of the removed panel is preserved. So we aren't destroying them after switching to another one.
The weird thing is how a map behaves:

e.g. before removing the panel it looks like this:
![image](https://cloud.githubusercontent.com/assets/11911179/16204649/31c40b7e-3720-11e6-9893-ed272e843615.png)

After readding like this:
![image](https://cloud.githubusercontent.com/assets/11911179/16204660/3ffeb04a-3720-11e6-96f4-8a47bc5f6f72.png)

The markers are perfectly fine but zoom and center are all over the place. I tried to debug this issue a little bit. After readding the zoom and center values in GoogleMapState are exactly the same than they where before removing it. It looks like the client state get's out of sync with the server state.

**Comment by tapioaali** [comment]
I'll take a look on this and hopefully this will be fixed in the next version.

**Comment by thinwire** [comment]
This project is no longer being maintained here. It has moved to [https://github.com/parttio/Google-Maps-for-Vaadin](https://github.com/parttio/Google-Maps-for-Vaadin)

Thanks.
