### ISSUE TITLE
Can't close info window

### ISSUE THREAD

**Issue by drongoong** [tapioaali/GoogleMapsVaadin7#44]
When you try to close the info windows - nothing happens. Problem is in `com.vaadin.tapio.googlemaps.client.GoogleMapWidget#setInfoWindows` .

**Comment by drongoong** [comment]
I will fix it by myself and make the pull request

**Comment by thinwire** [comment]
This project is no longer being maintained here. It has moved to [https://github.com/parttio/Google-Maps-for-Vaadin](https://github.com/parttio/Google-Maps-for-Vaadin)

Thanks.
