### ISSUE TITLE
GoogleMapMarker icon from Resource

### ISSUE THREAD

**Issue by balazsborjan** [tapioaali/GoogleMapsVaadin7#47]
Hi Tapio!

Is there any way to set the GoogleMapMarker icon with Resource parameter? I really want and need to do it, but the class only allows to set it with a String (url). 
I can't add it to the object, because I get it in Resource file from server which not i'm developed.

Can U help me with this issue?

Thanks,
Balázs

**Comment by thinwire** [comment]
Hi,

Unfortunately Tapio is no longer maintaining this project, he's left it to me. Now, the easiest way to change the marker would be to add the icon to your server-side theme, then extract the URL from a ThemeResource and set that.
(Initial impression, get back to me if that doesn't work)

**Comment by thinwire** [comment]
This project is no longer being maintained here. It has moved to [https://github.com/parttio/Google-Maps-for-Vaadin](https://github.com/parttio/Google-Maps-for-Vaadin)

Thanks.
