### ISSUE TITLE
Vaadin 8 support

### ISSUE THREAD

**Issue by tstsogoo** [tapioaali/GoogleMapsVaadin7#48]

**Comment by redshift72** [comment]
Any info or timeline for Vaadin 8 support?

**Comment by thinwire** [comment]
A Vaadin 8 version would be a good time to rewrite some of the project, but
unfortunately it's too big of an undertaking right now - we'd need to
allocate two weeks of work time for that, I can't do it on regular
"community project" time (which is 10% of all work time, schedule
permitting).

Patches welcome.

**Comment by thinwire** [comment]
This project is no longer being maintained here. It has moved to [https://github.com/parttio/Google-Maps-for-Vaadin](https://github.com/parttio/Google-Maps-for-Vaadin)

Thanks.
