### ISSUE TITLE
Chrome console gives "RetiredVersion" and "SensorNotRequired" warnings

### ISSUE THREAD

**Issue by fabcan** [tapioaali/GoogleMapsVaadin7#51]
Opening the online demo with Chrome and inspecting the console gives the following warnings: 

* https://developers.google.com/maps/documentation/javascript/error-messages#retired-version
* https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required

**Comment by thinwire** [comment]
This project is no longer being maintained here. It has moved to [https://github.com/parttio/Google-Maps-for-Vaadin]

Thanks.

**Comment by macrozone** [comment]
@thinwire there is no issue tracker there.
